#!/bin/sh
mount -t sysfs -o nodev,noexec,nosuid none /sys
mount -t proc -o nodev,noexec,nosuid none /proc

mknod -m 0666 /dev/null c 1 3

/sbin/mdev -s

# mkdir -p /var/log
mkdir -p /home /tmp
chmod 777 /tmp

touch /etc/passwd
touch /etc/group
# adduser root -u 0
echo -e '\n' | adduser root -u 0
addgroup users

chmod a=rw,o=r /etc/passwd /etc/group

ifconfig eth0 10.0.2.15
route add default gw 10.0.2.2

ifconfig lo up
udhcpc -b

# mkdir /var/run -p

syslogd
ldconfig -v
dropbear
# ntpd -p 0.ubuntu.pool.ntp.org &

chmod a=w /dev/null
chmod a=r /dev/urandom /dev/zero

# try this without internet ?
# mkdir -p /etc/dropbear
# dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key
# dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key
echo -e "\033[0;31mpress ctrl+] to kill qemu\033[0m"
